apiVersion: cdi.kubevirt.io/v1beta1
kind: VolumeImportSource
metadata:
  name: base-vm-import-source
  namespace: vms-test
spec:
  source:
    registry:
      url: "docker://registry.redhat.io/rhel9/rhel-guest-image:9.4-1175"
      pullMethod: node
