apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: base-vm-disk
  namespace: vms-test
spec:
  dataSourceRef:
    apiGroup: cdi.kubevirt.io
    kind: VolumeImportSource
    name: base-vm-import-source
  accessModes:
    - ReadWriteMany
  volumeMode: Block
  storageClassName: rx-csi-replicated
  resources:
    requests:
      storage: 30Gi
